In [16]:
import re
import nltk
from nltk.corpus import stopwords

In [17]:
import pandas as pd

In [18]:
import numpy as np

In [19]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.zeros((3,3))
a
b
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
a

array([1, 2, 3])

In [22]:
b

array([4, 5, 6])

In [30]:
c.shape[1]

3

## One Hot Encoding

In [32]:
data = {1: "The food is good",2: "The food is bad",3: "Pizza is good"}

In [33]:
data

{1: 'The food is good', 2: 'The food is bad', 3: 'Pizza is good'}

In [34]:
from nltk.stem import WordNetLemmatizer

In [35]:
lemmatizer = WordNetLemmatizer()

In [36]:
from nltk.tokenize import word_tokenize

In [37]:
from nltk.corpus import stopwords

In [38]:
stop_words = stopwords.words('english')

In [39]:
uniq_words = []
vis = set()
for _ , v in data.items():
    for word in word_tokenize(v):
        if word not in vis:
            vis.add(word)
            uniq_words.append([word])


In [40]:
vector = [0]*len(uniq_words)
oneHotEncod = {}

for i in range(len(uniq_words)):
    v = vector.copy()
    v[i] = 1
    oneHotEncod[uniq_words[i]] = v

    


In [41]:
oneHotEncod

{'The': [1, 0, 0, 0, 0, 0],
 'food': [0, 1, 0, 0, 0, 0],
 'is': [0, 0, 1, 0, 0, 0],
 'good': [0, 0, 0, 1, 0, 0],
 'bad': [0, 0, 0, 0, 1, 0],
 'Pizza': [0, 0, 0, 0, 0, 1]}

In [42]:
data_v = {}
for k , v in data.items():
    vector = []
    for word in word_tokenize(v):
        vector.append(oneHotEncod[word])
    data_v[k] = np.array(vector)

In [43]:
data_v

{1: array([[1, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0, 0]]),
 2: array([[1, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1, 0]]),
 3: array([[0, 0, 0, 0, 0, 1],
        [0, 0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0, 0]])}

In [44]:
from sklearn.preprocessing import OneHotEncoder

In [63]:
uniq_words = []
vis = set()
for _ , v in data.items():
    for word in word_tokenize(v):
        if word not in vis:
            vis.add(word)
            uniq_words.append([word])

In [65]:
uniq_words

[['The'], ['food'], ['is'], ['good'], ['bad'], ['Pizza']]

In [79]:
vectors = OneHotEncoder(sparse_output = False).fit_transform(uniq_words)